version: '3'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=&{DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=&{DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST_AUTH_METHOD= trust
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
      
  app:
    build: .
    env_file:
      - .env
    tty: true
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    #python manage.py migrate &&
    ports:
      - '8001:8000'
    depends_on:
      - db

  celery:
    build: .
    tty: true
    command: celery -A project worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: celery -A project beat -l INFO -S django 
    depends_on:
      - redis
      - app

volumes:
  pg_data: 