version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5435:5432'
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: >
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db  