# Generated by Django 4.2.5 on 2023-09-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coursesubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_to_video',
            field=models.CharField(default='https://www.youtube.com/', max_length=80, verbose_name='ссылка на видео'),
            preserve_default=False,
        ),
    ]
